In [1]:
import torch
import numpy as np
from torchvision.transforms import ToTensor

In [2]:
t = torch.tensor(np.arange(12).reshape(2,2,3))  # [h,w,c]

In [3]:
t

tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]], dtype=torch.int32)

In [4]:
# [h,w,c] ---> [c,h,w]
t.view([3,2,2])  # 形状变成[3,2,2],但是这样的形状转换破坏了原有的数据结构

tensor([[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11]]], dtype=torch.int32)

In [5]:
t.transpose(1,2).transpose(0,1) # 经过两次转置将C拿到第一位才是 [C, H, W]

tensor([[[ 0,  3],
         [ 6,  9]],

        [[ 1,  4],
         [ 7, 10]],

        [[ 2,  5],
         [ 8, 11]]], dtype=torch.int32)

In [6]:
t1 = torch.tensor(np.arange(24).reshape(2,4,3))

In [7]:
t1

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17],
         [18, 19, 20],
         [21, 22, 23]]], dtype=torch.int32)

In [8]:
ToTensor()(t1.numpy())

tensor([[[ 0,  3,  6,  9],
         [12, 15, 18, 21]],

        [[ 1,  4,  7, 10],
         [13, 16, 19, 22]],

        [[ 2,  5,  8, 11],
         [14, 17, 20, 23]]], dtype=torch.int32)

In [9]:
t.permute(2,0,1) # permute可以一次移动多个轴

tensor([[[ 0,  3],
         [ 6,  9]],

        [[ 1,  4],
         [ 7, 10]],

        [[ 2,  5],
         [ 8, 11]]], dtype=torch.int32)

In [10]:
t.max()

tensor(11, dtype=torch.int32)

In [11]:
t

tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]], dtype=torch.int32)

In [13]:
t.size()

torch.Size([2, 2, 3])

In [14]:
t.max(dim=-1)

torch.return_types.max(
values=tensor([[ 2,  5],
        [ 8, 11]], dtype=torch.int32),
indices=tensor([[2, 2],
        [2, 2]]))