In [8]:
import torch
import numpy as np

In [3]:
torch.__version__

'1.4.0'

In [7]:
type(torch.tensor([1, 2, 3]))

torch.Tensor

In [9]:
torch.tensor(np.arange(15).reshape(3,5))

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]], dtype=torch.int32)

In [10]:
torch.empty([3,4])

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [11]:
torch.ones([2,2])

tensor([[1., 1.],
        [1., 1.]])

In [12]:
torch.zeros([3,4])

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [13]:
# 创建两行三列的随机值，随机值的范围是0~1
torch.rand(2, 3)

tensor([[0.1715, 0.2475, 0.8071],
        [0.8678, 0.8223, 0.2502]])

In [14]:
# 创建两行两列的随机值，随机值的范围是low到high之间的整数
torch.randint(low=0, high=9, size=[2, 2])

tensor([[0, 1],
        [1, 7]])

In [16]:
# 创建三行四列的随机数，随机数的分布式均值为0，方差为1，符合正态分布
torch.randn([3, 4])

tensor([[ 1.2885, -1.4104, -1.7664, -0.5627],
        [-0.1976, -0.4961, -2.4654, -1.7287],
        [-1.1307, -1.0995,  1.1540, -1.2219]])

### 张量的属性和方法

In [17]:
a = torch.tensor([[[1]]])

In [18]:
a.item()

1

In [19]:
t = a.numpy()

In [20]:
type(t)

numpy.ndarray

In [26]:
a = torch.tensor(np.arange(30).reshape(3,2,5))
a

tensor([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9]],

        [[10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]],

        [[20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29]]], dtype=torch.int32)

In [24]:
a.size()

torch.Size([3, 2, 5])

In [28]:
a.size(-1)

5

In [29]:
a.view([1,30])

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
         18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]], dtype=torch.int32)

In [34]:
b = torch.tensor(np.arange(15).reshape(3,5))
b

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]], dtype=torch.int32)

In [35]:
b.transpose(0, 1)

tensor([[ 0,  5, 10],
        [ 1,  6, 11],
        [ 2,  7, 12],
        [ 3,  8, 13],
        [ 4,  9, 14]], dtype=torch.int32)

In [37]:
b.view(5, 3)

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]], dtype=torch.int32)

In [42]:
b[1, 2]

tensor(7, dtype=torch.int32)

In [43]:
b

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]], dtype=torch.int32)

In [41]:
b[1, :]

tensor([5, 6, 7, 8, 9], dtype=torch.int32)

In [46]:
b[:2, 0:2]

tensor([[0, 1],
        [5, 6]], dtype=torch.int32)

In [47]:
b.dtype

torch.int32

In [49]:
c = torch.ones([2,3], dtype=torch.float64)

In [50]:
c.dtype

torch.float64

### CUDA类型的tensor

In [51]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [52]:
device

device(type='cuda')

In [53]:
a

tensor([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9]],

        [[10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]],

        [[20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29]]], dtype=torch.int32)

In [54]:
a.device

device(type='cpu')

In [55]:
a.to(device)

tensor([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9]],

        [[10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]],

        [[20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29]]], device='cuda:0', dtype=torch.int32)

In [56]:
a.cpu().device

device(type='cpu')